#!/usr/bin/env bun
import fs from 'node:fs'
import path from 'node:path'
/**
 * deploy-config.ts · 机器级部署配置的读写 + 合并
 *
 * Subcommands (CLI 由后续 Task 实现)：
 *   check  - 检查必需 key 是否齐全（env + file 合并后）
 *   save   - 读 stdin JSON，写入配置文件（0600）
 *   load   - 输出 `export KEY=VALUE` 多行供 shell eval
 */

export const CONFIG_KEYS = ['WEID_DEPLOY_SERVER', 'WEID_REMOTE_PATH', 'WEID_SITE_URL'] as const
export type ConfigKey = (typeof CONFIG_KEYS)[number]

const REQUIRED_KEYS: readonly ConfigKey[] = ['WEID_DEPLOY_SERVER', 'WEID_SITE_URL']

export interface DeployConfig {
  WEID_DEPLOY_SERVER?: string
  WEID_REMOTE_PATH?: string
  WEID_SITE_URL?: string
}

export type CheckResult =
  | { status: 'ok'; values: Required<Pick<DeployConfig, 'WEID_DEPLOY_SERVER' | 'WEID_SITE_URL'>> & DeployConfig }
  | { status: 'missing'; missing: ConfigKey[]; present: DeployConfig }

const EXPORT_LINE_RE = /^\s*(?:export\s+)?([A-Z_][A-Z0-9_]*)=(.*)$/

function stripQuotes(value: string): string {
  const trimmed = value.trim()
  if (trimmed.length >= 2) {
    const first = trimmed[0]
    const last = trimmed[trimmed.length - 1]
    if ((first === '"' && last === '"') || (first === "'" && last === "'")) {
      return trimmed.slice(1, -1)
    }
  }

  return trimmed
}

export function parseConfigFile(raw: string): DeployConfig {
  const result: DeployConfig = {}
  for (const line of raw.split('\n')) {
    const trimmed = line.trim()
    if (!trimmed || trimmed.startsWith('#')) continue

    const match = EXPORT_LINE_RE.exec(trimmed)
    if (!match) continue

    const key = match[1]
    if ((CONFIG_KEYS as readonly string[]).includes(key)) {
      result[key as ConfigKey] = stripQuotes(match[2])
    }
  }

  return result
}

export function mergeConfig(fromFile: DeployConfig, fromEnv: DeployConfig): DeployConfig {
  const merged: DeployConfig = {}
  for (const key of CONFIG_KEYS) {
    const envValue = fromEnv[key]
    const fileValue = fromFile[key]
    if (envValue !== undefined && envValue !== '') {
      merged[key] = envValue
    } else if (fileValue !== undefined && fileValue !== '') {
      merged[key] = fileValue
    }
  }

  return merged
}

export function checkRequired(cfg: DeployConfig): CheckResult {
  const missing = REQUIRED_KEYS.filter((key) => !cfg[key])
  if (missing.length === 0) {
    return {
      status: 'ok',
      values: cfg as CheckResult extends { status: 'ok'; values: infer V } ? V : never,
    }
  }

  return {
    status: 'missing',
    missing,
    present: cfg,
  }
}

export function serializeConfigFile(cfg: DeployConfig): string {
  const lines = ['# generated by /publish · do not edit by hand unless you mean it']
  for (const key of CONFIG_KEYS) {
    const value = cfg[key]
    if (value !== undefined && value !== '') {
      lines.push(`export ${key}=${value}`)
    }
  }

  return `${lines.join('\n')}\n`
}

const SAFE_SHELL_RE = /^[A-Za-z0-9@._:/\-+=]+$/

export function shellEscape(value: string): string {
  if (SAFE_SHELL_RE.test(value)) {
    return value
  }

  return `'${value.replace(/'/g, `'\\''`)}'`
}

export function resolveConfigPath(): string {
  const xdg = process.env.XDG_CONFIG_HOME
  if (xdg) {
    return path.join(xdg, 'weid.fun', 'deploy.env')
  }

  const home = process.env.HOME
  if (!home) {
    throw new Error('deploy-config: neither XDG_CONFIG_HOME nor HOME is set')
  }

  return path.join(home, '.config', 'weid.fun', 'deploy.env')
}

export function loadFromFile(filePath: string = resolveConfigPath()): DeployConfig {
  if (!fs.existsSync(filePath)) return {}

  let raw: string
  try {
    raw = fs.readFileSync(filePath, 'utf-8')
  } catch (err) {
    throw new Error(`deploy-config: cannot read ${filePath}: ${(err as Error).message}`)
  }

  return parseConfigFile(raw)
}

function envAsConfig(): DeployConfig {
  const result: DeployConfig = {}
  for (const key of CONFIG_KEYS) {
    const value = process.env[key]
    if (value !== undefined && value !== '') {
      result[key] = value
    }
  }

  return result
}

function runCheck(): number {
  let fileConfig: DeployConfig
  try {
    fileConfig = loadFromFile()
  } catch (err) {
    process.stdout.write(
      `${JSON.stringify({ status: 'error', reason: 'file-unreadable', message: (err as Error).message })}\n`,
    )
    return 1
  }

  const merged = mergeConfig(fileConfig, envAsConfig())
  const result = checkRequired(merged)
  process.stdout.write(`${JSON.stringify(result)}\n`)
  return result.status === 'ok' ? 0 : 1
}

async function main() {
  const sub = process.argv[2]
  switch (sub) {
    case 'check':
      process.exit(runCheck())
      return
    default:
      process.stderr.write('Usage: deploy-config.ts <check|save|load>\n')
      process.exit(1)
  }
}

if (import.meta.main) {
  main().catch((err) => {
    process.stderr.write(`[deploy-config] fatal: ${(err as Error).message}\n`)
    process.exit(1)
  })
}
