import { describe, expect, test } from 'bun:test'
import {
  CONFIG_KEYS,
  type DeployConfig,
  checkRequired,
  mergeConfig,
  parseConfigFile,
  serializeConfigFile,
  shellEscape,
} from './deploy-config.ts'

describe('deploy-config · parseConfigFile', () => {
  test('parses standard export lines', () => {
    const raw = [
      '# generated by /publish',
      'export WEID_DEPLOY_SERVER=root@10.14.0.1',
      'export WEID_REMOTE_PATH=/var/www/weid.fun/',
      'export WEID_SITE_URL=https://weid.fun',
      '',
    ].join('\n')

    const parsed = parseConfigFile(raw)
    expect(parsed.WEID_DEPLOY_SERVER).toBe('root@10.14.0.1')
    expect(parsed.WEID_REMOTE_PATH).toBe('/var/www/weid.fun/')
    expect(parsed.WEID_SITE_URL).toBe('https://weid.fun')
  })

  test('ignores unknown keys and malformed lines', () => {
    const parsed = parseConfigFile('export SOMETHING=else\ngarbage\nexport WEID_DEPLOY_SERVER=user@host')
    expect(parsed.WEID_DEPLOY_SERVER).toBe('user@host')
    expect('SOMETHING' in parsed).toBe(false)
  })

  test('strips surrounding quotes on values', () => {
    const parsed = parseConfigFile('export WEID_SITE_URL="https://weid.fun"\nexport WEID_DEPLOY_SERVER=\'root@host\'')
    expect(parsed.WEID_SITE_URL).toBe('https://weid.fun')
    expect(parsed.WEID_DEPLOY_SERVER).toBe('root@host')
  })
})

describe('deploy-config · mergeConfig', () => {
  test('process env overrides file', () => {
    const merged = mergeConfig(
      { WEID_DEPLOY_SERVER: 'from-file@host' },
      { WEID_DEPLOY_SERVER: 'from-env@host' },
    )
    expect(merged.WEID_DEPLOY_SERVER).toBe('from-env@host')
  })

  test('file fills in missing env keys', () => {
    const merged = mergeConfig(
      { WEID_REMOTE_PATH: '/var/www/weid.fun/' },
      { WEID_DEPLOY_SERVER: 'env@host' },
    )
    expect(merged.WEID_DEPLOY_SERVER).toBe('env@host')
    expect(merged.WEID_REMOTE_PATH).toBe('/var/www/weid.fun/')
  })

  test('missing keys stay undefined', () => {
    const merged = mergeConfig({}, {})
    expect(merged.WEID_DEPLOY_SERVER).toBeUndefined()
  })
})

describe('deploy-config · checkRequired', () => {
  test('returns ok when all required present', () => {
    const result = checkRequired({
      WEID_DEPLOY_SERVER: 'root@host',
      WEID_SITE_URL: 'https://weid.fun',
      WEID_REMOTE_PATH: '/var/www/weid.fun/',
    })
    expect(result.status).toBe('ok')
  })

  test('returns missing for required only (REMOTE_PATH optional)', () => {
    const result = checkRequired({ WEID_REMOTE_PATH: '/var/www/weid.fun/' })
    expect(result.status).toBe('missing')
    if (result.status === 'missing') {
      expect(result.missing).toContain('WEID_DEPLOY_SERVER')
      expect(result.missing).toContain('WEID_SITE_URL')
      expect(result.missing).not.toContain('WEID_REMOTE_PATH')
    }
  })
})

describe('deploy-config · serializeConfigFile', () => {
  test('round-trips through parseConfigFile', () => {
    const cfg: DeployConfig = {
      WEID_DEPLOY_SERVER: 'root@10.14.0.1',
      WEID_REMOTE_PATH: '/var/www/weid.fun/',
      WEID_SITE_URL: 'https://weid.fun',
    }

    const serialized = serializeConfigFile(cfg)
    expect(serialized.startsWith('# generated by /publish')).toBe(true)

    const reparsed = parseConfigFile(serialized)
    expect(reparsed).toEqual(cfg)
  })

  test('only writes keys that exist', () => {
    const serialized = serializeConfigFile({ WEID_DEPLOY_SERVER: 'root@host' })
    expect(serialized).toContain('WEID_DEPLOY_SERVER=root@host')
    expect(serialized).not.toContain('WEID_REMOTE_PATH')
    expect(serialized).not.toContain('WEID_SITE_URL')
  })
})

describe('deploy-config · shellEscape', () => {
  test('wraps values containing spaces or special chars in single quotes', () => {
    expect(shellEscape('/var/www/with space/')).toBe(`'/var/www/with space/'`)
    expect(shellEscape('a$b')).toBe(`'a$b'`)
  })

  test('leaves safe values unquoted', () => {
    expect(shellEscape('root@10.14.0.1')).toBe('root@10.14.0.1')
    expect(shellEscape('https://weid.fun')).toBe('https://weid.fun')
    expect(shellEscape('/var/www/weid.fun/')).toBe('/var/www/weid.fun/')
  })

  test('escapes embedded single quotes', () => {
    expect(shellEscape("it's")).toBe(`'it'\\''s'`)
  })
})

describe('deploy-config · CONFIG_KEYS', () => {
  test('exports exactly three keys in stable order', () => {
    expect(CONFIG_KEYS).toEqual(['WEID_DEPLOY_SERVER', 'WEID_REMOTE_PATH', 'WEID_SITE_URL'])
  })
})
